import AccessTime from "@mui/icons-material/AccessTime";
import AccountCircleOutlined from "@mui/icons-material/AccountCircleOutlined";
import Add from "@mui/icons-material/Add";
import AltRouteOutlined from "@mui/icons-material/AltRouteOutlined";
import ArrowDownward from "@mui/icons-material/ArrowDownward";
import ArrowForward from "@mui/icons-material/ArrowForward";
import ArrowUpward from "@mui/icons-material/ArrowUpward";
import BarChartOutlined from "@mui/icons-material/BarChartOutlined";
import PaymentsOutlined from "@mui/icons-material/PaymentsOutlined";
import CancelOutlined from "@mui/icons-material/CancelOutlined";
import CellTower from "@mui/icons-material/CellTower";
import CheckOutlined from "@mui/icons-material/Check";
import CheckCircleOutlined from "@mui/icons-material/CheckCircleOutlined";
import ChevronLeftOutlined from "@mui/icons-material/ChevronLeft";
import ChevronRightOutlined from "@mui/icons-material/ChevronRight";
import Close from "@mui/icons-material/Close";
import CloudOutlined from "@mui/icons-material/CloudOutlined";
import CreateNewFolderOutlined from "@mui/icons-material/CreateNewFolderOutlined";
import ContentPaste from "@mui/icons-material/ContentPaste";
import FolderCopyOutlined from "@mui/icons-material/FolderCopyOutlined";
import FolderOutlined from "@mui/icons-material/FolderOutlined";
import HubOutlined from "@mui/icons-material/HubOutlined";
import InsertDriveFileOutlined from "@mui/icons-material/InsertDriveFileOutlined";
import KeyboardReturn from "@mui/icons-material/KeyboardReturn";
import LayersOutlined from "@mui/icons-material/LayersOutlined";
import NoteAddOutlined from "@mui/icons-material/NoteAddOutlined";
import RemoveOutlined from "@mui/icons-material/RemoveOutlined";
import SearchOff from "@mui/icons-material/SearchOff";
import SelectAll from "@mui/icons-material/SelectAll";
import ViewSidebarOutlined from "@mui/icons-material/ViewSidebarOutlined";
import ContentCopy from "@mui/icons-material/ContentCopy";
import DashboardOutlined from "@mui/icons-material/DashboardOutlined";
import DeleteOutlined from "@mui/icons-material/DeleteOutlined";
import CreditCardOutlined from "@mui/icons-material/CreditCardOutlined";
import DnsOutlined from "@mui/icons-material/DnsOutlined";
import DownloadIcon from "@mui/icons-material/Download";
import DragIndicator from "@mui/icons-material/DragIndicator";
import EditOutlined from "@mui/icons-material/EditOutlined";
import ErrorOutlined from "@mui/icons-material/ErrorOutlined";
import ExpandMore from "@mui/icons-material/ExpandMore";
import FilterList from "@mui/icons-material/FilterList";
import FilterListOff from "@mui/icons-material/FilterListOff";
import GitHub from "@mui/icons-material/GitHub";
import GroupOutlined from "@mui/icons-material/GroupOutlined";
import HistoryOutlined from "@mui/icons-material/History";
import ImageOutlined from "@mui/icons-material/ImageOutlined";
import InfoOutlined from "@mui/icons-material/InfoOutlined";
import LockOutlined from "@mui/icons-material/LockOutlined";
import MemoryOutlined from "@mui/icons-material/MemoryOutlined";
import Menu from "@mui/icons-material/Menu";
import MenuBookOutlined from "@mui/icons-material/MenuBookOutlined";
import MoreHoriz from "@mui/icons-material/MoreHoriz";
import NorthEast from "@mui/icons-material/NorthEast";
import NotificationsActiveOutlined from "@mui/icons-material/NotificationsActiveOutlined";
import NotificationsOffOutlined from "@mui/icons-material/NotificationsOffOutlined";
import OpenInNew from "@mui/icons-material/OpenInNew";
import PersonOutlined from "@mui/icons-material/PersonOutlined";
import PlayArrow from "@mui/icons-material/PlayArrow";
import PlaylistAddCheck from "@mui/icons-material/PlaylistAddCheck";
import PublicOutlined from "@mui/icons-material/PublicOutlined";
import Refresh from "@mui/icons-material/Refresh";
import RotateRight from "@mui/icons-material/RotateRight";
import SaveOutlined from "@mui/icons-material/SaveOutlined";
import SearchOutlined from "@mui/icons-material/Search";
import SendOutlined from "@mui/icons-material/SendOutlined";
import SettingsOutlined from "@mui/icons-material/SettingsOutlined";
import ShowChartOutlined from "@mui/icons-material/ShowChartOutlined";
import Speed from "@mui/icons-material/Speed";
import Stop from "@mui/icons-material/Stop";
import StorageOutlined from "@mui/icons-material/StorageOutlined";
import StorefrontOutlined from "@mui/icons-material/StorefrontOutlined";
import SwapVert from "@mui/icons-material/SwapVert";
import TerminalOutlined from "@mui/icons-material/TerminalOutlined";
import TimerOutlined from "@mui/icons-material/TimerOutlined";
import Tune from "@mui/icons-material/Tune";
import UploadIconMui from "@mui/icons-material/Upload";
import ViewStreamOutlined from "@mui/icons-material/ViewStreamOutlined";
import Visibility from "@mui/icons-material/Visibility";
import VisibilityOff from "@mui/icons-material/VisibilityOff";
import VpnKeyOutlined from "@mui/icons-material/VpnKeyOutlined";
import WarningAmberOutlined from "@mui/icons-material/WarningAmberOutlined";
import WifiOutlined from "@mui/icons-material/WifiOutlined";
import WifiOffOutlined from "@mui/icons-material/WifiOffOutlined";
import { wrapMuiIcon } from "@/utils/iconHelper";

export const Activity = wrapMuiIcon(ShowChartOutlined);
export const AlertCircle = wrapMuiIcon(ErrorOutlined);
export const AlertTriangle = wrapMuiIcon(WarningAmberOutlined);
export const ArrowDown = wrapMuiIcon(ArrowDownward);
export const ArrowRight = wrapMuiIcon(ArrowForward);
export const ArrowUp = wrapMuiIcon(ArrowUpward);
export const ArrowUpDown = wrapMuiIcon(SwapVert);
export const BellOff = wrapMuiIcon(NotificationsOffOutlined);
export const BellRing = wrapMuiIcon(NotificationsActiveOutlined);
export const BookOpen = wrapMuiIcon(MenuBookOutlined);
export const ChartNoAxesCombined = wrapMuiIcon(BarChartOutlined);
export const Check = wrapMuiIcon(CheckOutlined);
export const CheckIcon = Check;
export const CheckCircle2 = wrapMuiIcon(CheckCircleOutlined);
export const ChevronDown = wrapMuiIcon(ExpandMore);
export const ChevronLeft = wrapMuiIcon(ChevronLeftOutlined);
export const ChevronRight = wrapMuiIcon(ChevronRightOutlined);
export const CircleAlert = wrapMuiIcon(ErrorOutlined);
export const CircleDollarSign = wrapMuiIcon(PaymentsOutlined);
export const CircleGauge = wrapMuiIcon(Speed);
export const Clock = wrapMuiIcon(AccessTime);
export const Clock3 = wrapMuiIcon(AccessTime);
export const Cloud = wrapMuiIcon(CloudOutlined);
export const Copy = wrapMuiIcon(ContentCopy);
export const CornerRightUp = wrapMuiIcon(NorthEast);
export const Cpu = wrapMuiIcon(MemoryOutlined);
export const Database = wrapMuiIcon(StorageOutlined);
export const DatabaseZap = wrapMuiIcon(StorageOutlined);
export const Download = wrapMuiIcon(DownloadIcon);
export const ExternalLink = wrapMuiIcon(OpenInNew);
export const Eye = wrapMuiIcon(Visibility);
export const EyeOff = wrapMuiIcon(VisibilityOff);
export const Filter = wrapMuiIcon(FilterList);
export const FilterOff = wrapMuiIcon(FilterListOff);
export const Github = wrapMuiIcon(GitHub);
export const Globe = wrapMuiIcon(PublicOutlined);
export const Gauge = wrapMuiIcon(Speed);
export const GripVertical = wrapMuiIcon(DragIndicator);
export const HardDrive = wrapMuiIcon(StorageOutlined);
export const History = wrapMuiIcon(HistoryOutlined);
export const Image = wrapMuiIcon(ImageOutlined);
export const ImageIcon = Image;
export const Info = wrapMuiIcon(InfoOutlined);
export const KeyRound = wrapMuiIcon(VpnKeyOutlined);
export const LayoutDashboard = wrapMuiIcon(DashboardOutlined);
export const ListChecks = wrapMuiIcon(PlaylistAddCheck);
export const Loader2 = wrapMuiIcon(Refresh);
export const LoaderCircle = wrapMuiIcon(Refresh);
export const LockKeyhole = wrapMuiIcon(LockOutlined);
export const MemoryStick = wrapMuiIcon(ViewStreamOutlined);
export const MenuIcon = wrapMuiIcon(Menu);
export const MoreHorizontal = wrapMuiIcon(MoreHoriz);
export const Pencil = wrapMuiIcon(EditOutlined);
export const Play = wrapMuiIcon(PlayArrow);
export const Plus = wrapMuiIcon(Add);
export const PlusIcon = Plus;
export const Radar = wrapMuiIcon(CellTower);
export const RefreshCw = wrapMuiIcon(Refresh);
export const RotateCw = wrapMuiIcon(RotateRight);
export const Route = wrapMuiIcon(AltRouteOutlined);
export const Save = wrapMuiIcon(SaveOutlined);
export const Search = wrapMuiIcon(SearchOutlined);
export const Send = wrapMuiIcon(SendOutlined);
export const Server = wrapMuiIcon(DnsOutlined);
export const Settings = wrapMuiIcon(SettingsOutlined);
export const Settings2 = wrapMuiIcon(Tune);
export const SlidersHorizontal = wrapMuiIcon(Tune);
export const Square = wrapMuiIcon(Stop);
export const SquareArrowOutUpRight = wrapMuiIcon(OpenInNew);
export const Store = wrapMuiIcon(StorefrontOutlined);
export const Terminal = wrapMuiIcon(TerminalOutlined);
export const Timer = wrapMuiIcon(TimerOutlined);
export const Trash = wrapMuiIcon(DeleteOutlined);
export const Trash2 = Trash;
export const Trash2Icon = Trash;
export const Upload = wrapMuiIcon(UploadIconMui);
export const UploadIcon = Upload;
export const User = wrapMuiIcon(PersonOutlined);
export const UserCircle = wrapMuiIcon(AccountCircleOutlined);
export const Users = wrapMuiIcon(GroupOutlined);
export const WalletCards = wrapMuiIcon(CreditCardOutlined);
export const Wifi = wrapMuiIcon(WifiOutlined);
export const WifiOff = wrapMuiIcon(WifiOffOutlined);
export const X = wrapMuiIcon(Close);
export const XCircle = wrapMuiIcon(CancelOutlined);
export const MinusIcon = wrapMuiIcon(RemoveOutlined);
export const Edit2Icon = Pencil;
export const Layers3 = wrapMuiIcon(LayersOutlined);
export const Network = wrapMuiIcon(HubOutlined);
export const SearchX = wrapMuiIcon(SearchOff);
export const SquareTerminal = Terminal;
export const ClipboardPaste = wrapMuiIcon(ContentPaste);
export const ClipboardCopy = Copy;
export const ClipboardList = wrapMuiIcon(ContentPaste);
export const File = wrapMuiIcon(InsertDriveFileOutlined);
export const FileIcon = File;
export const FilePlus2 = wrapMuiIcon(NoteAddOutlined);
export const Folder = wrapMuiIcon(FolderOutlined);
export const FolderPlus = wrapMuiIcon(CreateNewFolderOutlined);
export const CornerDownLeft = wrapMuiIcon(KeyboardReturn);
export const Files = wrapMuiIcon(FolderCopyOutlined);
export const PanelRightClose = wrapMuiIcon(ViewSidebarOutlined);
export const TextSelect = wrapMuiIcon(SelectAll);
